### ISSUE TITLE
Is is possible to show a message in px-overlay component

### ISSUE THREAD

**Issue by contactrajiv08** [PredixDev/px-overlay#1]
Hi,

I am using  px-overlay component to block the UI for users till a process completes. Meanwhile the process is running, i want to show a message like 'Loading data...' in the center of the overlay. Please suggest if it is possible using px-overlay or in some other way i can achieve this.

See below screenshot for example:

![untitled](https://cloud.githubusercontent.com/assets/7464756/19353867/6680e4a6-9182-11e6-88cd-ab3f07850fd8.png)

Thanks,
Rajiv

**Comment by ugurk** [comment]
Is there any reason for not allowing content inside overlay?
