### ISSUE TITLE
Position of Overlay does not work properly with Firefox/Safari9 and IE11.

### ISSUE THREAD

**Issue by tanahiro** [PredixDev/px-overlay#2]
When I access the demo page of the px-overlay (https://www.predix-ui.com/#/components/px-overlay/) with Firefox (51.0.1 (32-bit) on Windows 7) and click the button 'click me to get (light|dark) overlay', the overlay component appears, but when I scroll down and up, the position of the overlay component is not correct like in the screenshot below.

![px-overlay](https://cloud.githubusercontent.com/assets/379684/23613249/f73cf6e8-027e-11e7-8374-eb4ccad4ad22.png)

**Comment by ppeyro** [comment]
Same behavior in Safari9 and IE11 as well.

**Comment by nonmetalhail** [comment]
Closing this as the overlay component has been removed in v2.0.0.
