### ISSUE TITLE
Update overlay demo to clarify click behavior

### ISSUE THREAD

**Issue by brettjohns89** [PredixDev/px-overlay#3]
## Expected behavior and actual behavior:

In the demo, the overlay automatically closes when you click anywhere on the screen. However, the component itself does not appear to have this functionality. Once the overlay is on the screen there's no way to get it to go away without refreshing the page. 

## Steps to reproduce the problem:
Import and use the px-overlay component without writing your own on-click function to close the overlay. 

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):
px-overlay v 0.4.4, all browsers, Windows 7

## Screenshots (_optional, but very helpful_):

You can see right in the codepen example linked on the demo page that the overlay does not close when you click on it. The demo on the predix-ui page does not match the actual functionality of the component. 

https://www.predix-ui.com/#/components/px-overlay/

**Comment by nonmetalhail** [comment]
Correct; not everyone would want this functionality, such as if you have a modal, you may only want the overlay to close based on the button clicks from the modal. So it is up to the developer to decide when and how to close the overlay.

**Comment by brettjohns89** [comment]
This should be made clear in the demo and documentation.  I thought I had somehow invoked the element incorrectly when it did not work in my project the way that it did in the demo. The demo should not be showcasing functionality that doesn't actually exist in the element, or at the very least it should be documented that to get this functionality you need to write it yourself.

**Comment by nonmetalhail** [comment]
Agreed; we'll add some verbage or make another change to try and make that clear that it is a demo artifact.

**Comment by randyaskin** [comment]
Fixed in v1.
